### ISSUE TITLE
Function Declarations and Expressions link broken

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Learn-JavaScript#14]
Use the appropriate links in the function declarations README topic to fill in the correct link on the main README file.

## Links Affected 
- [x] Function Declarations
- [x] Function Expressions 
- [x] Conclusion
- [x] Code File

## Issue Source
https://github.com/Evavic44/Learn-JavaScript#03-function-decleration-vs-expressions

## Solution Source
- [Function Declararions and Expressions](https://github.com/Evavic44/Learn-JavaScript/tree/main/02-Fundamentals-Part-2/02_functions_declerations_expressions)

**Comment by AlessandroCipolletti** [comment]
Hi @Evavic44 I'm new here. Can I take this simple one, just to start ?

**Comment by AlessandroCipolletti** [comment]
I just submitted a pull request :)

**Comment by Evavic44** [comment]
> Hi @Evavic44 I'm new here. Can I take this simple one, just to start ?

Sorry for the late response, @AlessandroCipolletti. I'm checking your PR now.
