### ISSUE TITLE
📄 Structure sections and arrange Readme content

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Learn-JavaScript#2]
Simplify the file structure to make the readme file more readable and keep focus.

## Solutions to try
- [x] Create separate folders for each section.
- [x] Add Readme file inside folders.
- [x] Add links and headings in the main Readme for easy navigation.

**Comment by jmoldyvan** [comment]
if the goal is to make the readme files more easily accessible, would a solution be to break up the main read.me into separate files and spread them across the chapters?
I guess that is the ask for this issue, just want to make sure

**Comment by Evavic44** [comment]
> if the goal is to make the readme files more easily accessible, would a solution be to break up the main read.me into separate files and spread them across the chapters? I guess that is the ask for this issue, just want to make sure

Creating a separate Readme for each section is exactly what I had in mind. 
I see you've made a PR. Nice... Let me review it, quickly.

**Comment by Evavic44** [comment]
Nice work on separating the files and creating their own Readme inside. That was a ton of work. 🎉

The final solution would be to link each section to the main [README.md](https://github.com/Evavic44/Learn-JavaScript#readme) file.

## Expected Changes
Would each section to be separated by a heading and a link you can click to visit it.

A great example is this repo: https://github.com/MichaelCade/90DaysOfDevOps
