### ISSUE TITLE
Link Sections using appropriate links

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/Learn-JavaScript#5]
Use the headings to link each respective section in the Main README file.

Example

- 📄 [What is JavaScript](https://github.com/Evavic44/Learn-JavaScript/blob/main) will be linked to https://github.com/Evavic44/Learn-JavaScript/tree/main/01-Fundamentals-Part-1/00_introduction

# Sections Linked
Thick the sections as appropriate. This will help us keep track of what links have been successfully added.

1. Introduction

 - [x] 📄 [What is JavaScript](https://github.com/Mount-Blanc/Learn-JavaScript/tree/main/01-Fundamentals-Part-1/00_introduction#what-is-javascript)
 - [x]  🟡 [Hello World in JavaScript](https://github.com/Mount-Blanc/Learn-JavaScript/blob/main/01-Fundamentals-Part-1/01_hello_world/Hello_world.js)
  - [x] 📄 [What do we use JavaScript for](https://github.com/Mount-Blanc/Learn-JavaScript/tree/main/01-Fundamentals-Part-1/01_hello_world#what-do-we-use-javascript-for)
  - [x]  📄 [JavaScript Releases](https://github.com/Mount-Blanc/Learn-JavaScript/tree/main/01-Fundamentals-Part-1/01_hello_world#javascript-releases)

2. How to link JavaScript file

 - [x]  🟡 [Inline Linking](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x] 🟡 [External Linking](https://github.com/Evavic44/Learn-JavaScript/blob/main)

3. Values and Variables

 - [x] 📄 [Definition of Values](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [ ]📄 [Definition of Variables](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x] 🟡 [Variable Naming Convention](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x] 🟡 [Rules and Reserved Keywords](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x] 🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

4. Data Types

  - [x]  📄 [Definition of Data Types](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  📄 [The 7 Primitive Data Types](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

5. Let, Const, Var

  - [ ]  📄 [Ways to declare a Variable](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [ ]  📄 [When to use Var](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [ ]  📄 [Let](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [ ]  📄 [Const](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [ ]  📄 [Let or Const](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

6. Operators

  - [x]  📄 [Basic Operators](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  📄 [Arithimetic Operators](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  📄 [Assignment Operators](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  📄 [Comparison Operators](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x] 🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

7. Operator Precedence

  - [x] 📄 [Definition of Operator Precedence](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x] 🔗 [MDN Docs Reference](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

8. Coding Challenge One 🎉

  - [x]  📄 [Coding Challenge](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  🟡 [Solution](https://github.com/Evavic44/Learn-JavaScript/blob/main)

9. String & Template Literals

  - [x]  📄 [Strings](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  📄 [Template Literals](https://github.com/Evavic44/Learn-JavaScript/blob/main)
  - [x]  🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

10. Taking Decisions (If/Else)

 - [x]   📄 [Conditional Statements](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [If Statement](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Else Statement](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Else If Statement](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

11. Coding Challenge Two 🎉

 - [x]   📄 [Coding Challenge](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Solution](https://github.com/Evavic44/Learn-JavaScript/blob/main)

12. Type Conversion & Coercion

 - [x]   📄 [Definition](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Type Conversion](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Type Coercion](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

13. Truthy & Falsy Values

 - [x]   📄 [Definition of Truthy & Falsy Values](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

14. Equality Operator

 - [x]  📄 [Strict Equality Operator ===](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Loose Equality Operator ==](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Differential Equality Operator !==](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]  🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

15. Boolean Logic

 - [x]   📄 [Defintion of Boolean Logic](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [AND Operator](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [OR Operator](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [NOT Operator](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [How do Logical Operators Work?](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

16. Logical Operators

 - [x]   📄 [Definition of Logical Operators](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

17. Coding Challenge Three 🎉

 - [x]   📄 [Coding Challenge](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Solution](https://github.com/Evavic44/Learn-JavaScript/blob/main)

18. Switch Statement

 - [x]   📄 [What are Switch Statements?](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Break](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   📄 [Default](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

19. Statements & Expressions

 - [x]   📄 [Introduction to Statements & Expression](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

20. Conditional (Ternary) Operator

 - [x]   📄 [Introduction to Ternary Operator](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Code File](https://github.com/Evavic44/Learn-JavaScript/blob/main)

21. Coding Challenge Four 🎉

 - [x]   📄 [Coding Challenge](https://github.com/Evavic44/Learn-JavaScript/blob/main)
 - [x]   🟡 [Solution](https://github.com/Evavic44/Learn-JavaScript/blob/main)

**Comment by Mount-Blanc** [comment]
Hello, I would like to work on this issue. Just one thing to confirm. In the Main README file each section has a code file. By code file you mean the script.js file?

**Comment by Evavic44** [comment]
Hey, @Mount-Blanc Yes. the code files are the `Script.js` file.

I hope every other thing is clear? If not, I will recommend you do like the first topic to test it out and if it is okay, you can work on the rest. 


Starting with the Introduction.

1. Introduction

   - 📄 [What is JavaScript](https://github.com/Evavic44/Learn-JavaScript/blob/main)
   - 🟡 [Hello World in JavaScript](https://github.com/Evavic44/Learn-JavaScript/blob/main)
   - 📄 [What do we use JavaScript for](https://github.com/Evavic44/Learn-JavaScript/blob/main)
   - 📄 [JavaScript Releases](https://github.com/Evavic44/Learn-JavaScript/blob/main)

**Comment by Mount-Blanc** [comment]
Hey @Evavic44, I noticed that there is a numbering mismatch of the main README and the 01-fundamentals-part 1 README's 


**00-04 are not numbered in the README. Example:**
![Good number](https://user-images.githubusercontent.com/102170589/168167329-81f2bdb0-7125-4941-ba15-f73cee400fc5.png)

**05-21 are numbered incorrectly compared to the main README. Example:**
![bad number](https://user-images.githubusercontent.com/102170589/168167365-ca0254b8-8f2b-424a-bc74-d18c67af42bd.png)
**MainREADME**
![main](https://user-images.githubusercontent.com/102170589/168168482-ce633f39-fff6-4177-afd1-2b24c7959bdc.png)

I just wanted to bring this to your attention.

**Comment by Evavic44** [comment]
Oh, yes. I see that. You can leave those links empty and I'll figure it out when I'm done. I'm merging the ones you've done so far. Thanks a lot.

**Comment by Evavic44** [comment]
Thanks for fixing the bug. :smile:
